version: "3.8"

### Uses a network within Docker to allow Pi-Hole and Unbound to communicate.
### Exposes pihole and unbound ports on the same ports on the host machine. 
### Any requests to these ports on the host machine will route to containers.

### Modeled on https://github.com/IAmStoxe/wirehole and https://hub.docker.com/r/klutchell/unbound/

services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    restart: unless-stopped
    ports:
      - '5053:5053/udp'
    volumes:
      - './unbound:/opt/unbound/etc/unbound/'
    networks:
      internal:
        ipv4_address: 10.2.0.200
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - '53:53'
      - '53:53/udp'
      - '80:80'
      - '443:443'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEB_PASS}
      ServerIP: ${HOST_IP}
      DNS1: 10.2.0.200
      DNS2: 10.2.0.200
    cap_add:
      - NET_ADMIN
    dns:
      - '127.0.0.1'
      - '10.2.0.200'
    networks:
      internal:
        ipv4_address: 10.2.0.100

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
